<a href="https://colab.research.google.com/github/aishwaryasharmaccoew/NeuralNets/blob/main/NoisePerturbImages.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Perturb your dataset by adding noise, and saving the performance results**

Noise will be Gaussian-distributed with approximately 10 percent cross-section (e.g., 25 noise pixels out of 16x16 = 256 pixels per image) and have zero mean, and standard deviation of (0.001, 0.002, 0.003, 0.005, 0.01, 0.02, 0.03, 0.05, and 0.1) .Then repeat this with noise at 20 percent, 25 percent, 30 percent, and 35 percent cross-section

**Algorithm:**   

1.  Generate random noise with std-dev as described above,
2.  Add noise values to input image
3.  Renormalize the noise-corrupted image so all of its pixels have values in the interval [0,1]. 

In [9]:
import numpy as np
import tensorflow as tf
import random
from random import seed


In [17]:
#code to create perturbed dataset

def perturb_dataset(path,pcs):
  image=np.load(path)

  seed(1)

  mean =0
  stddev= [0.001,0.002,0.003,0.005,0.01,0.02,0.03,0.05,0.1]
  #randomly select x,y pixels to modify
  stride = random.randint(round(0.5*pcs), round(1.5*pcs))
  print(stride)
  print("-----------")

  dataset=[]
  for std in stddev:
      print('For stddev :',std)
      for img in image:
          #original image
          perturbed_img=[]
          perturbed_img.append(img)
          img=img.flatten()

          gaus_noise = np.random.normal(mean, std, img.shape)
          gaus_noise=gaus_noise.flatten()
          p=0
          while(p<256):
              img[p]= img[p]+gaus_noise[p]
              p=p+stride
          #noise added   
          perturbed_img.append(img.reshape(16,16))
          dataset.append(perturbed_img)
          
  np.save("perturbed_data_"+str(pcs)+".npy", np.asarray(dataset))
  return np.asarray(dataset)

In [21]:
# Call the function for multiple std like    
#perturb_dataset(path,percentCrossSectionValue)
image= perturb_dataset("/content/Font1.npy",35)

26
-----------
For stddev : 0.001
For stddev : 0.002
For stddev : 0.003
For stddev : 0.005
For stddev : 0.01
For stddev : 0.02
For stddev : 0.03
For stddev : 0.05
For stddev : 0.1


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:34: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


In [22]:
#stride values 7,14,16,19,26
# To load dataset :  img[0] -- original image, img[1] -- perturbed image



print(image.shape)
for img in image:
    print(img[0])
    print(img[1])
    break

(324, 2)
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0
 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0
 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0
 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1]
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 